xchk_core/urls.py
from django.urls import path
from django.conf.urls import include

from . import views, contentviews

app_name = 'checkerapp'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('create_repo', views.CreateRepoView.as_view(), name='create_repo'),
    path('content/impossible_node', contentviews.ImpossibleNodeView.as_view(), name=f'{contentviews.ImpossibleNodeView.uid}_view'),
    path('nodes/feedback/<int:node_pk>', views.node_feedback_view, name='node_feedback_view'),
    path('courses/overview', views.all_courses_overview_view, name='all_courses_overview_view'),
    path('courses/<course_title>', views.new_course_view, name='new_course_view'),
    path('courses/maps/<course_title>', views.course_map_view, name='course_map_view'),
    path('courses/maps/<course_title>/<uid>', views.course_local_map_view, name='course_local_map_view'),
    path('courses/feedback/<int:course_pk>', views.course_feedback_view, name='course_feedback_view'),
    path('repos/delete/<int:pk>', views.DeleteRepoView.as_view(), name='delete_repo_view'),
    path('notifications/', include("pinax.notifications.urls",namespace="pinax_notifications")),
]

xchk_core/templates/xchk_core/all_courses_overview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
Test!
{{ courses }}
{% endblock %}

xchk_core/templates/xchk_core/course_map.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<canvas id="springydemo" width="960" height="1000px"/>
{% endblock %}

{% block javascript %}
{{ block.super }}
<script src="{% static 'xchk_core/js/springy.js' %}"></script>
<script src="{% static 'xchk_core/js/springyui.js' %}"></script>
{{ graph|json_script:"graph" }}
<script>
$(window).on('load', function() {
  const data = JSON.parse(document.getElementById('graph').textContent);
  let graph = new Springy.Graph();
  let nodes = {}
  // dependency pair: object and a list of strings (node UID's)
  // object has title field and URL field
  // first make node objects for all dependents and their dependencies
  for (dependency_pair_idx in data) {
    let dependent = data[dependency_pair_idx][0]
    if (!(dependent.title in nodes)) {
	    let dependent_color = '#000000';
	    if (dependent.completed) {
		dependent_color = '#298030';
	    }
	    if(dependent.locked) {
		dependent_color = '#aaaaaa';
	    }
	    nodes[dependent.title] = graph.newNode({ label : dependent.title, url : dependent.url, color : dependent_color, onclick : function() {
window.location.href = dependent.url
}});
    }
    for (dependency_idx in data[dependency_pair_idx][1]) {
      let dependency = data[dependency_pair_idx][1][dependency_idx]
      let dependency_color = '#000000';
      if (dependency.completed) {
          dependency_color = '#298030';
      }
      if(dependency.locked) {
          dependency_color = '#aaaaaa';
      }
      if (!(dependency.title in nodes)) {
	      nodes[dependency.title] = graph.newNode({ label : dependency.title, url : dependency.url, color : dependency_color,onclick : function() {
window.location.href = dependency.url
} });
      }
    }
  }
  for (dependency_pair_idx in data) {
    let dependent = data[dependency_pair_idx][0]
    for (dependency_idx in data[dependency_pair_idx][1]) {
      let dependency = data[dependency_pair_idx][1][dependency_idx]
      graph.newEdge(nodes[dependency.title],nodes[dependent.title]);
    }
  }
  jQuery(function(){
    let springy = window.springy = jQuery('#springydemo').springy({
      graph: graph,
    });
  });
}); 
</script>
{% endblock %}

xchk_core/templates/xchk_core/course_overview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if repo_id %}
<p class="alert alert-info">Zorg eerst dat je Git geïnstalleerd en geconfigureerd hebt. Instructies om dit te doen staan op de hoofdpagina. Daarna kan je volgend commando uitvoeren:
<code>{{ clone_command }}</code>
</p>
{% endif %}
{{ toc|safe }}
{% if repo_id %}
<p><a href="{% url 'checkerapp:delete_repo_view' repo_id %}">Mijn repository voor deze cursus verwijderen.</a></p>
{% endif %}
{% endblock %}

{% block javascript %}
{{ block.super }}
{{ supplied_dependencies|json_script:"supplied_dependencies" }}
<script>
dependencies = JSON.parse(document.getElementById('supplied_dependencies').textContent);
markWithDependencies = function(uid) {
  var icon = $("i").filter(function() { return $(this).attr('for_cv_uid') === uid });
  icon.addClass("dependency");
  var icon_dependencies = dependencies[uid];
  if (icon_dependencies) {
    for (dep in icon_dependencies) {
      markWithDependencies(icon_dependencies[dep]);
    }
  }
}
$(window).on('load', function() {
  $(".fa-crosshairs").click(
    function(e) {
      $('*').removeClass('dependency');
      markWithDependencies($(this).attr('for_cv_uid'));
    }
  );
}); 
</script>
{% endblock %}

xchk_core/templates/xchk_core/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Van start gaan met xchk</h1>
<p>Om met xchk te werken, moet je enkele setupstappen doorlopen. Deze worden voorgedaan in onderstaande filmpjes, die je in volgorde moet doorlopen:</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/J60gDypbxAA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<iframe width="560" height="315" src="https://www.youtube.com/embed/glAMnsCr4tY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<iframe width="560" height="315" src="https://www.youtube.com/embed/RsmioORgZoQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<iframe width="560" height="315" src="https://www.youtube.com/embed/TmoKMk3TqlE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>Hieronder vind je ook een demonstratie van het gebruik van xchk: hoe je oefeningen indient en hoe je de foutmeldingen gebruikt om je eigen oplossingen te verbeteren:</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/E2tXCZYmE2U" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
{% endblock %}

xchk_core/templates/xchk_core/repo_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
{% csrf_token %}
<p>Ben je zeker dat je {{ object }} wil verwijderen?</p>
<input type="submit">
</form>
{% endblock %}

xchk_core/templates/xchk_core/repo_does_not_exist.html
{% extends 'base.html' %}
{% block content %}
<p>Je hebt geen repository voor {{ course_title }}. Je moet inschrijven voor een cursus voor je de inhoud kan bekijken. Dit wordt <a href="https://www.youtube.com/watch?v=TmoKMk3TqlE">hier</a> uitgelegd.</p>
{% endblock content %}

xchk_core/templates/xchk_core/repo_exists.html
{% extends 'base.html' %}
{% block content %}
<p>Je hebt al een repository voor {{ course_title }}. Je kan er geen nieuwe aanmaken tenzij je de bestaande uit het systeem verwijdert. Als je denkt dat je dit wil doen, neem dan eerst contact op met je lector.</p>
{% endblock content %}

xchk_core/templates/xchk_core/repo_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
{% csrf_token %}
{{ form|crispy }}
<input type="submit">
</form>
{% endblock %}

xchk_core/templates/xchk_core/single_course_overview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if repo_id %}
<p class="alert alert-info">Zorg eerst dat je Git geïnstalleerd en geconfigureerd hebt. Instructies om dit te doen staan op de hoofdpagina. Daarna kan je volgend commando uitvoeren:
<code>{{ clone_command }}</code>
</p>
{% endif %}
{{ toc|safe }}
{% if repo_id %}
<p><a href="{% url 'checkerapp:delete_repo_view' repo_id %}">Mijn repository voor deze cursus verwijderen.</a></p>
{% endif %}
{% endblock %}

{% block javascript %}
{{ block.super }}
{{ supplied_dependencies|json_script:"supplied_dependencies" }}
<script>
dependencies = JSON.parse(document.getElementById('supplied_dependencies').textContent);
markWithDependencies = function(uid) {
  var icon = $("i").filter(function() { return $(this).attr('for_cv_uid') === uid });
  icon.addClass("dependency");
  var icon_dependencies = dependencies[uid];
  if (icon_dependencies) {
    for (dep in icon_dependencies) {
      markWithDependencies(icon_dependencies[dep]);
    }
  }
}
$(window).on('load', function() {
  $(".fa-crosshairs").click(
    function(e) {
      $('*').removeClass('dependency');
      markWithDependencies($(this).attr('for_cv_uid'));
    }
  );
}); 
</script>
{% endblock %}